[tools]
terraform = "1.11.4"
python = "3.13.3"
ruff = "latest"

[settings]
verbose = false

[env]
TF_CLI_ARGS_plan = "-compact-warnings"
TF_CLI_ARGS_apply = "-compact-warnings"

[env._.python.venv]
path = ".venv"
create = true

[tasks]
tf-format = "terraform fmt -recursive"
tf-validate = "terraform validate"

[tasks.tf-plan-system]
dir = "infrastructure/system"
run = "make tf-plan"

[tasks.tf-apply-system]
dir = "infrastructure/system"
run = "make tf-apply"

[tasks.tf-plan-user]
dir = "infrastructure/user"
run = "make tf-plan"

[tasks.tf-apply-user]
dir = "infrastructure/user"
run = "make tf-apply"

[tasks.p-install]
description = "Install dependencies"
alias = "pi"
dir = "lambda"
run = "uv pip install -r requirements.txt"

[tasks.p-run]
description = "Run the application"
alias = "pr"
dir = "lambda"
run = "python app.py"

[tasks.p-test]
description = "Run tests"
alias = "pt"
dir = "lambda"
run = "pytest tests/"

[tasks.p-lint]
description = "Lint the code"
alias = "pl"
dir = "lambda"
run = "ruff check --select ALL --fix"
