name: Build and tests lambda
on:
  pull_request:
jobs:
  lambda-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          version: 2025.5.6
          install: true
          install_args: ruff python
          cache: true
          working_directory: .
      - run: mise p-lint
      - run: mise p-test
